### ISSUE TITLE
basic interactive interface for hotel management system

### ISSUE THREAD

**Issue by Jackson-Webdev** [Jackson-Webdev/Python-projects#1]
i have been working on simple hotel management system using python and  the project is in its final stages, it needs basic interface allowing users to perform different tasks customer data and billing.

**Comment by HamzaSiddiquiii** [comment]
i will take on further code required to complete this project assign this issue to me

**Comment by Jackson-Webdev** [comment]
alright raise one PR for this issue

**Comment by Jackson-Webdev** [comment]
i tested and run the your additions to the code and it works perfectly Good job.

**Comment by Jackson-Webdev** [comment]
i tested your additions to this project and it is working perfectly.

**Comment by HamzaSiddiquiii** [comment]
Thanks, happy to help
